theme: jekyll-theme-minimal
title: Flutter Kit
description: Bootstrap your Flutter projects in seconds
show_downloads: true
github:
  repository_url: https://github.com/stevenosse/flutter_kit
branch: site
